### ISSUE TITLE
Support for Build Number? (I.e. 1.0.0+1)

### ISSUE THREAD

**Issue by rodydavis** [f3ath/pubspec-version#13]
Many times I want to bump just the build number and not the version number.

Ideally, it would take `1.0.0` or `1.0.0+1`

and bump it to `1.0.0+2`

**Comment by f3ath** [comment]
Good idea, but may take a bit of extra work. The version manipulations are made through [pubspec](https://pub.dartlang.org/packages/pubspec), not sure it it supports build number. If not< one would want to submit a PR to it.

**Comment by AppleEducate** [comment]
Ok great! I’ll do some research

**Comment by lemz90** [comment]
> Good idea, but may take a bit of extra work. The version manipulations are made through [pubspec](https://pub.dartlang.org/packages/pubspec), not sure if it supports build number. If not, one would want to submit a PR to it.

Not sure if implementing an incrementor for build number in [pubspec](https://pub.dartlang.org/packages/pubspec) will work because it is not required to be an int from my understanding.

I've added #14 which you can use to add a build version more easily.

**Comment by f3ath** [comment]
Version [0.5.0](https://pub.dev/packages/pubspec_version/versions/0.5.0) allows incrementing the build number. Please give it a try.

**Comment by AppleEducate** [comment]
Awesome thanks! I will try this tomorrow 😁

**Comment by f3ath** [comment]
Version [0.6.1]9https://pub.dev/packages/pubspec_version/versions/0.6.1) supports the `-b` flag to retain the build part when bumping major/minor/patch.
