### ISSUE TITLE
Allow updating {major,minor,patch} and build number

### ISSUE THREAD

**Issue by amitkot** [f3ath/pubspec-version#26]
I plan on using this for Flutter. As the build number is mandatory there (for iOS and Android versioning), any change that increments the version number will also require a build number increment for the new version to register as a new one on Android and iOS.

I was thinking of a syntax such as:

    $ pubver bump minor build

**Comment by f3ath** [comment]
Hi, thanks for the suggestion. That should be possible by running two commands at once, e.g. `pubver bump minor && pubver bump patch`. Would it work for you?

**Comment by amitkot** [comment]
Thinking about your suggestion, I guess what I want could be achieved by calling `pubver bump minor -b && pubver bump patch` (otherwise the patch number gets lost when bumping the minor).

Now I only wish it would #17 was resolved so that my comments and formatting wouldn't change.

Thanks!
